In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm
from matplotlib.cm import PRGn
import seaborn as sns
import calendar
from datetime import date
from datetime import datetime
plt.style.use('ggplot')
from pandas.tseries.holiday import USFederalHolidayCalendar as calendar

In [12]:
headway = pd.read_csv("../data/Headway_data.csv", nrows=1981716)

In [13]:
pd.set_option('display.max_columns', None)

In [14]:
headway.head(4)

,CALENDAR_ID,SERVICE_ABBR,ADHERENCE_ID,DATE,ROUTE_ABBR,BLOCK_ABBR,OPERATOR,TRIP_ID,OVERLOAD_ID,ROUTE_DIRECTION_NAME,TIME_POINT_ABBR,ROUTE_STOP_SEQUENCE,TRIP_EDGE,LATITUDE,LONGITUDE,SCHEDULED_TIME,ACTUAL_ARRIVAL_TIME,ACTUAL_DEPARTURE_TIME,ADHERENCE,SCHEDULED_HDWY,ACTUAL_HDWY,HDWY_DEV,ADJUSTED_EARLY_COUNT,ADJUSTED_LATE_COUNT,ADJUSTED_ONTIME_COUNT,STOP_CANCELLED,PREV_SCHED_STOP_CANCELLED,IS_RELIEF,BLOCK_STOP_ORDER,DWELL_IN_MINS
0,120211101,1,76447164,2021-11-01,7,1704,2088,297750,0,TO DOWNTOWN,HBHS,4.0,1,36.107575,-86.812719,14:10:00,13:59:21,14:12:00,-2.000000,14.0,15.983333,1.983333,0,0,1,0,0.0,0,2,12.650000
1,120211101,1,76447165,2021-11-01,7,1704,2088,297750,0,TO DOWNTOWN,21BK,3.0,0,36.138372,-86.800622,14:20:00,14:23:21,14:23:21,-3.350000,14.0,17.333333,3.333333,0,0,1,0,0.0,0,11,0.000000
2,120211101,1,76447166,2021-11-01,7,1704,2088,297750,0,TO DOWNTOWN,MCC5_9,2.0,2,36.167091,-86.781923,14:39:00,14:36:46,14:59:11,-20.183333,NaN,NaN,NaN,0,1,0,0,NaN,0,23,22.416666
3,120211101,1,76447167,2021-11-01,50,1704,2088,297749,0,TO DOWNTOWN,MLKS,7.0,1,36.161008,-86.800851,15:10:00,15:04:31,15:10:17,-0.283333,NaN,NaN,NaN,0,0,1,0,0.0,0,24,5.766666

In [15]:
headway.drop(headway.columns[[-1,-2, -3, -4, -5, -6, -7, -8]], axis = 1, inplace=True)

In [16]:
headway.head(3)

,CALENDAR_ID,SERVICE_ABBR,ADHERENCE_ID,DATE,ROUTE_ABBR,BLOCK_ABBR,OPERATOR,TRIP_ID,OVERLOAD_ID,ROUTE_DIRECTION_NAME,TIME_POINT_ABBR,ROUTE_STOP_SEQUENCE,TRIP_EDGE,LATITUDE,LONGITUDE,SCHEDULED_TIME,ACTUAL_ARRIVAL_TIME,ACTUAL_DEPARTURE_TIME,ADHERENCE,SCHEDULED_HDWY,ACTUAL_HDWY,HDWY_DEV
0,120211101,1,76447164,2021-11-01,7,1704,2088,297750,0,TO DOWNTOWN,HBHS,4.0,1,36.107575,-86.812719,14:10:00,13:59:21,14:12:00,-2.000000,14.0,15.983333,1.983333
1,120211101,1,76447165,2021-11-01,7,1704,2088,297750,0,TO DOWNTOWN,21BK,3.0,0,36.138372,-86.800622,14:20:00,14:23:21,14:23:21,-3.350000,14.0,17.333333,3.333333
2,120211101,1,76447166,2021-11-01,7,1704,2088,297750,0,TO DOWNTOWN,MCC5_9,2.0,2,36.167091,-86.781923,14:39:00,14:36:46,14:59:11,-20.183333,NaN,NaN,NaN

In [20]:
headway['DATE'] =  pd.to_datetime(headway['DATE'])

In [22]:
headway['WEEKDAY'] = [calendar.day_name[x.weekday()] for x in headway['DATE']]
headway.head()

AttributeError: type object 'USFederalHolidayCalendar' has no attribute 'day_name'

In [10]:
DOW = headway[['WEEKDAY','SCHEDULED_HDWY', 'ACTUAL_HDWY','ADHERENCE', 'ROUTE_ABBR']]

KeyError: "['WEEKDAY'] not in index"

In [23]:
#| works as an or operator 
summer = headway[(headway["DATE"] >= '2022-06-01') & (headway["DATE"] <= '2022-08-01')]
#headway['DATE'] > '2022-06-01') & (headway['DATE'] <= '2022-08-01')])]

In [24]:
summer['DATE'].value_counts()

2022-06-03    6451
2022-07-20    6441
2022-07-08    6438
2022-06-13    6431
2022-07-07    6428
              ...
2022-06-05    3674
2022-06-12    3674
2022-07-03    3673
2022-07-04    3671
2022-06-19    3645
Name: DATE, Length: 62, dtype: int64

RUSH_HOUR = []

for x in hw_clean['SCHEDULED_TIME']: if x >= '07:00:00' and x <= '09:30:00': RUSH_HOUR.append('Morning Rush') elif x >= '16:00:00' and x <= '18:00:00': RUSH_HOUR.append('Evening Rush') else: RUSH_HOUR.append('No Rush') RUSH_HOUR

In [25]:
summer.head(10)

,CALENDAR_ID,SERVICE_ABBR,ADHERENCE_ID,DATE,ROUTE_ABBR,BLOCK_ABBR,OPERATOR,TRIP_ID,OVERLOAD_ID,ROUTE_DIRECTION_NAME,TIME_POINT_ABBR,ROUTE_STOP_SEQUENCE,TRIP_EDGE,LATITUDE,LONGITUDE,SCHEDULED_TIME,ACTUAL_ARRIVAL_TIME,ACTUAL_DEPARTURE_TIME,ADHERENCE,SCHEDULED_HDWY,ACTUAL_HDWY,HDWY_DEV
1109085,120220601,1,85713482,2022-06-01,22,2200,1280,311622,0,TO DOWNTOWN,MHSP,14.0,1,36.178360,-86.845441,04:42:00,04:26:03,04:41:02,0.966666,NaN,NaN,NaN
1109086,120220601,1,85713483,2022-06-01,22,2200,1280,311622,0,TO DOWNTOWN,ELIZ,10.0,0,36.193454,-86.839981,04:46:00,04:45:38,04:45:38,0.366666,NaN,NaN,NaN
1109087,120220601,1,85713484,2022-06-01,22,2200,1280,311622,0,TO DOWNTOWN,CV23,5.0,0,36.182177,-86.814445,04:54:00,04:53:16,04:53:16,0.733333,NaN,NaN,NaN
1109088,120220601,1,85713485,2022-06-01,22,2200,1280,311622,0,TO DOWNTOWN,MCC5_10,1.0,2,36.167091,-86.781923,05:10:00,04:59:40,04:59:40,10.333333,NaN,NaN,NaN
1109089,120220601,1,85713486,2022-06-01,22,2200,1280,311641,0,FROM DOWNTOWN,MCC5_10,1.0,1,36.167091,-86.781923,05:15:00,04:59:40,05:17:15,-2.250000,NaN,NaN,NaN
1109090,120220601,1,85713487,2022-06-01,22,2200,1280,311641,0,FROM DOWNTOWN,CV23,5.0,0,36.183480,-86.814220,05:25:00,05:24:06,05:24:06,0.900000,NaN,NaN,NaN
1109091,120220601,1,85713488,2022-06-01,22,2200,1280,311641,0,FROM DOWNTOWN,MHSP,14.0,2,36.178360,-86.845441,05:32:00,05:31:04,05:31:04,0.933333,NaN,NaN,NaN
1109092,120220601,1,85713489,2022-06-01,22,2200,1280,311607,0,TO DOWNTOWN,MHSP,14.0,1,36.178360,-86.845441,05:42:00,05:31:04,05:41:02,0.966666,35.0,32.116666,-2.883334
1109093,120220601,1,85713490,2022-06-01,22,2200,1280,311607,0,TO DOWNTOWN,ELIZ,10.0,0,36.193454,-86.839981,05:46:00,05:46:32,05:46:32,-0.533333,35.0,33.500000,-1.500000
1109094,120220601,1,85713491,2022-06-01,22,2200,1280,311607,0,TO DOWNTOWN,CV23,5.0,0,36.182177,-86.814445,05:54:00,05:53:48,05:53:48,0.200000,15.0,15.250000,0.250000