In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:

weather = pd.read_csv("../data/bna_weather.csv", nrows=9740)

In [3]:
headway = pd.read_csv("../data/Headway_Data.csv", nrows=1981716)

pd.set_option allows you to see all columns   rest it pd.reset_option("max_columns")

In [4]:
pd.set_option('display.max_columns', None)

In [5]:
headway.head(10)

,CALENDAR_ID,SERVICE_ABBR,ADHERENCE_ID,DATE,ROUTE_ABBR,BLOCK_ABBR,OPERATOR,TRIP_ID,OVERLOAD_ID,ROUTE_DIRECTION_NAME,TIME_POINT_ABBR,ROUTE_STOP_SEQUENCE,TRIP_EDGE,LATITUDE,LONGITUDE,SCHEDULED_TIME,ACTUAL_ARRIVAL_TIME,ACTUAL_DEPARTURE_TIME,ADHERENCE,SCHEDULED_HDWY,ACTUAL_HDWY,HDWY_DEV,ADJUSTED_EARLY_COUNT,ADJUSTED_LATE_COUNT,ADJUSTED_ONTIME_COUNT,STOP_CANCELLED,PREV_SCHED_STOP_CANCELLED,IS_RELIEF,BLOCK_STOP_ORDER,DWELL_IN_MINS
0,120211101,1,76447164,2021-11-01,7,1704,2088,297750,0,TO DOWNTOWN,HBHS,4.0,1,36.107575,-86.812719,14:10:00,13:59:21,14:12:00,-2.000000,14.0,15.983333,1.983333,0,0,1,0,0.0,0,2,12.650000
1,120211101,1,76447165,2021-11-01,7,1704,2088,297750,0,TO DOWNTOWN,21BK,3.0,0,36.138372,-86.800622,14:20:00,14:23:21,14:23:21,-3.350000,14.0,17.333333,3.333333,0,0,1,0,0.0,0,11,0.000000
2,120211101,1,76447166,2021-11-01,7,1704,2088,297750,0,TO DOWNTOWN,MCC5_9,2.0,2,36.167091,-86.781923,14:39:00,14:36:46,14:59:11,-20.183333,NaN,NaN,NaN,0,1,0,0,NaN,0,23,22.416666
3,120211101,1,76447167,2021-11-01,50,1704,2088,297749,0,TO DOWNTOWN,MLKS,7.0,1,36.161008,-86.800851,15:10:00,15:04:31,15:10:17,-0.283333,NaN,NaN,NaN,0,0,1,0,0.0,0,24,5.766666
4,120211101,1,76447168,2021-11-01,50,1704,2088,297749,0,TO DOWNTOWN,MCC5_11,5.0,2,36.167091,-86.781923,15:27:00,15:16:59,15:16:59,10.016666,NaN,NaN,NaN,0,0,1,0,NaN,0,25,0.000000
5,120211101,1,76447969,2021-11-01,22,2200,1352,298143,0,TO DOWNTOWN,MHSP,15.0,1,36.178360,-86.845441,04:42:00,04:29:30,04:41:50,0.166666,NaN,NaN,NaN,0,0,1,0,0.0,0,2,12.333333
6,120211101,1,76447970,2021-11-01,22,2200,1352,298143,0,TO DOWNTOWN,ELIZ,11.0,0,36.193454,-86.839981,04:46:00,04:46:58,04:46:58,-0.966666,NaN,NaN,NaN,0,0,1,0,0.0,0,9,0.000000
7,120211101,1,76447971,2021-11-01,22,2200,1352,298143,0,TO DOWNTOWN,CV23,6.0,0,36.182177,-86.814445,04:54:00,04:55:00,04:55:00,-1.000000,NaN,NaN,NaN,0,0,1,0,0.0,0,19,0.000000
8,120211101,1,76447972,2021-11-01,22,2200,1352,298143,0,TO DOWNTOWN,MCC5_12,4.0,2,36.167091,-86.781923,05:10:00,05:05:26,05:05:26,4.566666,NaN,NaN,NaN,0,0,1,0,NaN,0,35,0.000000
9,120211101,1,76447973,2021-11-01,22,2200,1352,298162,0,FROM DOWNTOWN,MCC5_12,4.0,1,36.167091,-86.781923,05:15:00,05:05:26,05:16:49,-1.816666,NaN,NaN,NaN,0,0,1,0,0.0,0,36,11.383333

In [6]:
headway.dtypes

CALENDAR_ID                    int64
SERVICE_ABBR                   int64
ADHERENCE_ID                   int64
DATE                          object
ROUTE_ABBR                     int64
BLOCK_ABBR                     int64
OPERATOR                       int64
TRIP_ID                        int64
OVERLOAD_ID                    int64
ROUTE_DIRECTION_NAME          object
TIME_POINT_ABBR               object
ROUTE_STOP_SEQUENCE          float64
TRIP_EDGE                      int64
LATITUDE                     float64
LONGITUDE                    float64
SCHEDULED_TIME                object
ACTUAL_ARRIVAL_TIME           object
ACTUAL_DEPARTURE_TIME         object
ADHERENCE                    float64
SCHEDULED_HDWY               float64
ACTUAL_HDWY                  float64
HDWY_DEV                     float64
ADJUSTED_EARLY_COUNT           int64
ADJUSTED_LATE_COUNT            int64
ADJUSTED_ONTIME_COUNT          int64
STOP_CANCELLED                 int64
PREV_SCHED_STOP_CANCELLED    float64
IS_RELIEF                      int64
BLOCK_STOP_ORDER               int64
DWELL_IN_MINS                float64
dtype: object

In [7]:
headway.shape

(1981715, 30)

In [8]:
weather.shape

(9739, 46)

In [9]:
weather.shape

(9739, 46)

In [10]:
weather.head(10)

,Date,key,class,expire_time_gmt,obs_id,obs_name,valid_time_gmt,day_ind,temp,wx_icon,icon_extd,wx_phrase,pressure_tend,pressure_desc,dewPt,heat_index,rh,pressure,vis,wc,wdir,wdir_cardinal,gust,wspd,max_temp,min_temp,precip_total,precip_hrly,snow_hrly,uv_desc,feels_like,uv_index,qualifier,qualifier_svrty,blunt_phrase,terse_phrase,clds,water_temp,primary_wave_period,primary_wave_height,primary_swell_period,primary_swell_height,primary_swell_direction,secondary_swell_period,secondary_swell_height,secondary_swell_direction
0,2021-11-01 00:53:00,KBNA,observation,1635753180,KBNA,Nashville,1635745980,N,51,26,2600,Cloudy,1.0,Rising,43,51,74,29.59,10.0,51.0,360.0,N,NaN,9.0,68.0,51.0,NaN,0.0,NaN,Low,51.0,0.0,NaN,NaN,NaN,NaN,OVC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-11-01 01:30:00,KBNA,observation,1635755400,KBNA,Nashville,1635748200,N,50,29,2900,Partly Cloudy,NaN,NaN,42,50,74,29.59,10.0,50.0,350.0,N,NaN,8.0,NaN,NaN,NaN,0.0,NaN,Low,50.0,0.0,NaN,NaN,NaN,NaN,SCT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-11-01 01:53:00,KBNA,observation,1635756780,KBNA,Nashville,1635749580,N,49,33,3300,Fair,NaN,NaN,42,49,77,29.59,10.0,47.0,350.0,N,NaN,6.0,NaN,NaN,NaN,0.0,NaN,Low,47.0,0.0,NaN,NaN,NaN,NaN,CLR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-11-01 02:53:00,KBNA,observation,1635760380,KBNA,Nashville,1635753180,N,48,33,3300,Fair,NaN,NaN,41,48,77,29.60,10.0,48.0,360.0,N,NaN,3.0,NaN,NaN,NaN,0.0,NaN,Low,48.0,0.0,NaN,NaN,NaN,NaN,CLR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-11-01 03:53:00,KBNA,observation,1635763980,KBNA,Nashville,1635756780,N,47,33,3300,Fair,1.0,Rising Rapidly,41,47,80,29.61,10.0,47.0,NaN,CALM,NaN,0.0,NaN,NaN,NaN,0.0,NaN,Low,47.0,0.0,NaN,NaN,NaN,NaN,CLR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2021-11-01 04:53:00,KBNA,observation,1635767580,KBNA,Nashville,1635760380,N,45,33,3300,Fair,NaN,NaN,40,45,82,29.63,8.0,45.0,310.0,NW,NaN,3.0,NaN,NaN,NaN,0.0,NaN,Low,45.0,0.0,NaN,NaN,NaN,NaN,CLR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2021-11-01 05:53:00,KBNA,observation,1635771180,KBNA,Nashville,1635763980,N,46,33,3300,Fair,NaN,NaN,41,46,83,29.63,10.0,43.0,320.0,NW,NaN,6.0,NaN,NaN,NaN,0.0,NaN,Low,43.0,0.0,NaN,NaN,NaN,NaN,CLR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2021-11-01 06:53:00,KBNA,observation,1635774780,KBNA,Nashville,1635767580,D,45,34,3400,Fair,1.0,Rising,40,45,82,29.65,9.0,41.0,360.0,N,NaN,7.0,NaN,NaN,NaN,0.0,NaN,Low,41.0,0.0,NaN,NaN,NaN,NaN,CLR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2021-11-01 07:53:00,KBNA,observation,1635778380,KBNA,Nashville,1635771180,D,47,34,3400,Fair,NaN,NaN,41,47,80,29.66,9.0,44.0,20.0,NNE,NaN,7.0,NaN,NaN,NaN,0.0,NaN,Low,44.0,0.0,NaN,NaN,NaN,NaN,CLR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2021-11-01 08:53:00,KBNA,observation,1635781980,KBNA,Nashville,1635774780,D,50,34,3400,Fair,NaN,NaN,42,50,74,29.69,10.0,50.0,20.0,NNE,NaN,6.0,NaN,NaN,NaN,0.0,NaN,Low,50.0,1.0,NaN,NaN,NaN,NaN,CLR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
headway['ROUTE_ABBR'].value_counts()

55    362259
56    355098
52    291150
23    250787
50    249880
3     216446
22    153074
7     103021
Name: ROUTE_ABBR, dtype: int64

In [12]:
headway.drop(headway.columns[[-1,-2]], axis = 1, inplace=True)

In [13]:
headway.shape

(1981715, 28)

In [14]:
headway.head(10)

,CALENDAR_ID,SERVICE_ABBR,ADHERENCE_ID,DATE,ROUTE_ABBR,BLOCK_ABBR,OPERATOR,TRIP_ID,OVERLOAD_ID,ROUTE_DIRECTION_NAME,TIME_POINT_ABBR,ROUTE_STOP_SEQUENCE,TRIP_EDGE,LATITUDE,LONGITUDE,SCHEDULED_TIME,ACTUAL_ARRIVAL_TIME,ACTUAL_DEPARTURE_TIME,ADHERENCE,SCHEDULED_HDWY,ACTUAL_HDWY,HDWY_DEV,ADJUSTED_EARLY_COUNT,ADJUSTED_LATE_COUNT,ADJUSTED_ONTIME_COUNT,STOP_CANCELLED,PREV_SCHED_STOP_CANCELLED,IS_RELIEF
0,120211101,1,76447164,2021-11-01,7,1704,2088,297750,0,TO DOWNTOWN,HBHS,4.0,1,36.107575,-86.812719,14:10:00,13:59:21,14:12:00,-2.000000,14.0,15.983333,1.983333,0,0,1,0,0.0,0
1,120211101,1,76447165,2021-11-01,7,1704,2088,297750,0,TO DOWNTOWN,21BK,3.0,0,36.138372,-86.800622,14:20:00,14:23:21,14:23:21,-3.350000,14.0,17.333333,3.333333,0,0,1,0,0.0,0
2,120211101,1,76447166,2021-11-01,7,1704,2088,297750,0,TO DOWNTOWN,MCC5_9,2.0,2,36.167091,-86.781923,14:39:00,14:36:46,14:59:11,-20.183333,NaN,NaN,NaN,0,1,0,0,NaN,0
3,120211101,1,76447167,2021-11-01,50,1704,2088,297749,0,TO DOWNTOWN,MLKS,7.0,1,36.161008,-86.800851,15:10:00,15:04:31,15:10:17,-0.283333,NaN,NaN,NaN,0,0,1,0,0.0,0
4,120211101,1,76447168,2021-11-01,50,1704,2088,297749,0,TO DOWNTOWN,MCC5_11,5.0,2,36.167091,-86.781923,15:27:00,15:16:59,15:16:59,10.016666,NaN,NaN,NaN,0,0,1,0,NaN,0
5,120211101,1,76447969,2021-11-01,22,2200,1352,298143,0,TO DOWNTOWN,MHSP,15.0,1,36.178360,-86.845441,04:42:00,04:29:30,04:41:50,0.166666,NaN,NaN,NaN,0,0,1,0,0.0,0
6,120211101,1,76447970,2021-11-01,22,2200,1352,298143,0,TO DOWNTOWN,ELIZ,11.0,0,36.193454,-86.839981,04:46:00,04:46:58,04:46:58,-0.966666,NaN,NaN,NaN,0,0,1,0,0.0,0
7,120211101,1,76447971,2021-11-01,22,2200,1352,298143,0,TO DOWNTOWN,CV23,6.0,0,36.182177,-86.814445,04:54:00,04:55:00,04:55:00,-1.000000,NaN,NaN,NaN,0,0,1,0,0.0,0
8,120211101,1,76447972,2021-11-01,22,2200,1352,298143,0,TO DOWNTOWN,MCC5_12,4.0,2,36.167091,-86.781923,05:10:00,05:05:26,05:05:26,4.566666,NaN,NaN,NaN,0,0,1,0,NaN,0
9,120211101,1,76447973,2021-11-01,22,2200,1352,298162,0,FROM DOWNTOWN,MCC5_12,4.0,1,36.167091,-86.781923,05:15:00,05:05:26,05:16:49,-1.816666,NaN,NaN,NaN,0,0,1,0,0.0,0

In [15]:
headway.shape

(1981715, 28)

In [16]:
headway['TRIP_EDGE'].value_counts()

0    1209965
2     387235
1     384515
Name: TRIP_EDGE, dtype: int64

In [17]:
headway.head(10)

,CALENDAR_ID,SERVICE_ABBR,ADHERENCE_ID,DATE,ROUTE_ABBR,BLOCK_ABBR,OPERATOR,TRIP_ID,OVERLOAD_ID,ROUTE_DIRECTION_NAME,TIME_POINT_ABBR,ROUTE_STOP_SEQUENCE,TRIP_EDGE,LATITUDE,LONGITUDE,SCHEDULED_TIME,ACTUAL_ARRIVAL_TIME,ACTUAL_DEPARTURE_TIME,ADHERENCE,SCHEDULED_HDWY,ACTUAL_HDWY,HDWY_DEV,ADJUSTED_EARLY_COUNT,ADJUSTED_LATE_COUNT,ADJUSTED_ONTIME_COUNT,STOP_CANCELLED,PREV_SCHED_STOP_CANCELLED,IS_RELIEF
0,120211101,1,76447164,2021-11-01,7,1704,2088,297750,0,TO DOWNTOWN,HBHS,4.0,1,36.107575,-86.812719,14:10:00,13:59:21,14:12:00,-2.000000,14.0,15.983333,1.983333,0,0,1,0,0.0,0
1,120211101,1,76447165,2021-11-01,7,1704,2088,297750,0,TO DOWNTOWN,21BK,3.0,0,36.138372,-86.800622,14:20:00,14:23:21,14:23:21,-3.350000,14.0,17.333333,3.333333,0,0,1,0,0.0,0
2,120211101,1,76447166,2021-11-01,7,1704,2088,297750,0,TO DOWNTOWN,MCC5_9,2.0,2,36.167091,-86.781923,14:39:00,14:36:46,14:59:11,-20.183333,NaN,NaN,NaN,0,1,0,0,NaN,0
3,120211101,1,76447167,2021-11-01,50,1704,2088,297749,0,TO DOWNTOWN,MLKS,7.0,1,36.161008,-86.800851,15:10:00,15:04:31,15:10:17,-0.283333,NaN,NaN,NaN,0,0,1,0,0.0,0
4,120211101,1,76447168,2021-11-01,50,1704,2088,297749,0,TO DOWNTOWN,MCC5_11,5.0,2,36.167091,-86.781923,15:27:00,15:16:59,15:16:59,10.016666,NaN,NaN,NaN,0,0,1,0,NaN,0
5,120211101,1,76447969,2021-11-01,22,2200,1352,298143,0,TO DOWNTOWN,MHSP,15.0,1,36.178360,-86.845441,04:42:00,04:29:30,04:41:50,0.166666,NaN,NaN,NaN,0,0,1,0,0.0,0
6,120211101,1,76447970,2021-11-01,22,2200,1352,298143,0,TO DOWNTOWN,ELIZ,11.0,0,36.193454,-86.839981,04:46:00,04:46:58,04:46:58,-0.966666,NaN,NaN,NaN,0,0,1,0,0.0,0
7,120211101,1,76447971,2021-11-01,22,2200,1352,298143,0,TO DOWNTOWN,CV23,6.0,0,36.182177,-86.814445,04:54:00,04:55:00,04:55:00,-1.000000,NaN,NaN,NaN,0,0,1,0,0.0,0
8,120211101,1,76447972,2021-11-01,22,2200,1352,298143,0,TO DOWNTOWN,MCC5_12,4.0,2,36.167091,-86.781923,05:10:00,05:05:26,05:05:26,4.566666,NaN,NaN,NaN,0,0,1,0,NaN,0
9,120211101,1,76447973,2021-11-01,22,2200,1352,298162,0,FROM DOWNTOWN,MCC5_12,4.0,1,36.167091,-86.781923,05:15:00,05:05:26,05:16:49,-1.816666,NaN,NaN,NaN,0,0,1,0,0.0,0

In [19]:
headway['ROUTE_ABBR'].value_counts()

55    362259
56    355098
52    291150
23    250787
50    249880
3     216446
22    153074
7     103021
Name: ROUTE_ABBR, dtype: int64

In [21]:
headway['OPERATOR'].value_counts()

1147    15479
1587    15352
664     15268
409     14889
1020    14495
        ...
2091        1
2219        1
242         1
315         1
2310        1
Name: OPERATOR, Length: 458, dtype: int64